#.travis.yml

language: node_js
node_js:
  - "8.9.1"

branches:
  only:
    - master

script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    recipients:
      - me@selva070.me
    on_success: never # default: change
    on_failure: always # default: always
