#.travis.yml

language: node_js
branches:
  only:
    - master
script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    recipients:
      - me@selva070.me
    on_success: always # default: change
    on_failure: always # default: always
